import * as zlib from 'zlib';
import type { PurchaseInvoiceOrmEntity } from '../../infrastructure/persistence/purchase-invoice.orm-entity';
import {
  generatePurchaseRecordPdf,
  pdfSafe,
  purchaseRecordFields,
} from './purchase-record-pdf.generator';

function row(over: Partial<PurchaseInvoiceOrmEntity> = {}): PurchaseInvoiceOrmEntity {
  return {
    id: 'p1',
    merchantId: 'm',
    branchName: 'Main',
    spplrInvcNo: 'INV-77',
    supplierName: 'ABC <b>Supplies</b> \u{1F600} (Ltd)',
    supplierPin: 'P051234567X',
    receiptNo: 'INV-77',
    invoiceDate: '2026-08-20',
    subtotal: 100,
    vat: 16,
    total: 116,
    confirmationStatus: 'confirmed',
    erpSyncStatus: 'synced',
    erpBillNumber: 'BILL-9',
    erpPosting: { accountId: '1', accountName: 'Cost of Goods', lines: [] },
    rawKraResponse: null,
    kraConfirmInvcNo: 12,
    kraConfirmedAt: new Date('2026-08-21T10:00:00Z'),
    lineItems: [{ id: '1', description: 'Widget', hsCode: '', qty: 2, unitPrice: 50, taxRate: 16, taxAmount: 16, total: 116 }],
    ...over,
  } as PurchaseInvoiceOrmEntity;
}

/** Concatenates the text shown by every (deflated) content stream; pdfkit emits Helvetica text as hex TJ pieces. */
function pdfText(buf: Buffer): string {
  const raw = buf.toString('latin1');
  let text = '';
  for (const m of raw.matchAll(/stream\r?\n([\s\S]*?)endstream/g)) {
    let content: string;
    try {
      content = zlib.inflateSync(Buffer.from(m[1], 'latin1')).toString('latin1');
    } catch {
      continue;
    }
    for (const h of content.matchAll(/<([0-9a-fA-F]+)>/g)) {
      text += Buffer.from(h[1], 'hex').toString('latin1');
    }
    text += '\n';
  }
  return text;
}

describe('generatePurchaseRecordPdf', () => {
  it('returns a PDF titled Purchase Record, with the disclaimer, and no tax-invoice or receipt heading', async () => {
    const buf = await generatePurchaseRecordPdf(row());
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    const text = pdfText(buf);
    expect(text).toContain('Purchase Record');
    expect(text).toContain("Internal record - not a tax invoice or receipt. The supplier's tax invoice is the legal document.");
    expect(text).toContain('Generated by Sync2Books');
    expect(text).toContain('P051234567X');
    // Case-sensitive: the mandated disclaimer is lower-case, a heading would be upper-case.
    expect(text).not.toContain('TAX INVOICE');
    expect(text).not.toContain('RECEIPT');
  });

  it('copes with hostile and non-Latin text and many lines', async () => {
    const lines = Array.from({ length: 80 }, (_, i) => ({ id: String(i), description: `Item ${i} ‮\u0000 ${'x'.repeat(200)}`, hsCode: '', qty: 1, unitPrice: 1, taxRate: 16, taxAmount: 0.16, total: 1.16 }));
    const buf = await generatePurchaseRecordPdf(row({ lineItems: lines, supplierName: '\u0000‮中文' }));
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
  });

  it('prints the expected fields and the safe text only', () => {
    const f = Object.fromEntries(purchaseRecordFields(row()));
    expect(f['Supplier PIN']).toBe('P051234567X');
    expect(f['ERP bill number']).toBe('BILL-9');
    expect(f['ERP account']).toBe('Cost of Goods');
    expect(f['KRA confirmation reference']).toBe('12');
    expect(f['Supplier']).not.toMatch(/\u{1F600}/u);
    expect(pdfSafe(null)).toBe('-');
  });
});
