import * as PDFDocument from 'pdfkit';
import type { PurchaseInvoiceOrmEntity } from '../../infrastructure/persistence/purchase-invoice.orm-entity';

export const PURCHASE_RECORD_TITLE = 'Purchase Record';
export const PURCHASE_RECORD_DISCLAIMER =
  "Internal record - not a tax invoice or receipt. The supplier's tax invoice is the legal document.";
export const PURCHASE_RECORD_FOOTER = 'Generated by Sync2Books';

const BRAND = '#FF6123';
const INK = '#191A1A';

function money(n: number): string {
  const v = Number.isFinite(n) ? n : 0;
  return v.toLocaleString('en-KE', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso || '-';
  return `${String(d.getUTCDate()).padStart(2, '0')}/${String(d.getUTCMonth() + 1).padStart(2, '0')}/${d.getUTCFullYear()}`;
}

/** pdfkit's built-in Helvetica is WinAnsi only; anything outside printable Latin-1 becomes '?'. */
export function pdfSafe(value: unknown): string {
  if (value === null || value === undefined || value === '') return '-';
  return String(value)
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/[^\x20-\x7E -ÿ]/g, '?')
    .slice(0, 300);
}

function rawString(raw: Record<string, unknown> | null, key: string): string | null {
  const v = raw?.[key];
  return typeof v === 'string' && v.trim() ? v : null;
}

const CONFIRMATION_LABEL: Record<string, string> = {
  pulled: 'Pulled from KRA - not yet reviewed',
  pending_review: 'Pending review',
  confirmed: 'Confirmed with KRA',
  rejected: 'Rejected',
};

/** The label/value pairs printed in the header block, kept pure so they can be asserted on. */
export function purchaseRecordFields(
  row: PurchaseInvoiceOrmEntity,
): Array<[string, string]> {
  const raw = row.rawKraResponse;
  const fields: Array<[string, string]> = [
    ['Supplier', pdfSafe(row.supplierName)],
    ['Supplier PIN', pdfSafe(row.supplierPin)],
    ['Supplier invoice no.', pdfSafe(row.spplrInvcNo ?? row.receiptNo)],
    ['Branch', pdfSafe(row.branchName)],
    ['Invoice date', pdfSafe(formatDate(row.invoiceDate))],
    [
      'Confirmation status',
      pdfSafe(CONFIRMATION_LABEL[row.confirmationStatus] ?? row.confirmationStatus),
    ],
  ];
  if (row.kraConfirmedAt) {
    fields.push(['Confirmed at', pdfSafe(row.kraConfirmedAt.toISOString())]);
  }
  if (row.kraConfirmInvcNo !== null && row.kraConfirmInvcNo !== undefined) {
    fields.push(['KRA confirmation reference', pdfSafe(row.kraConfirmInvcNo)]);
  }
  const sdc = rawString(raw, 'sdcId');
  if (sdc) fields.push(['SDC', pdfSafe(sdc)]);
  const mrc = rawString(raw, 'mrcNo');
  if (mrc) fields.push(['MRC', pdfSafe(mrc)]);
  fields.push(['ERP status', row.erpSyncStatus === 'synced' ? 'Synced (open bill in ERP)' : pdfSafe(row.erpSyncStatus.replace(/_/g, ' '))]);
  if (row.erpBillNumber) fields.push(['ERP bill number', pdfSafe(row.erpBillNumber)]);
  if (row.erpPosting?.accountName) {
    fields.push(['ERP account', pdfSafe(row.erpPosting.accountName)]);
  }
  return fields;
}

export function generatePurchaseRecordPdf(
  row: PurchaseInvoiceOrmEntity,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 40,
      info: { Title: `${PURCHASE_RECORD_TITLE} ${pdfSafe(row.receiptNo)}`, Producer: 'Sync2Books' },
    });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = 40;
    const right = 555;

    doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(22).text(PURCHASE_RECORD_TITLE, left, 40);
    doc.fillColor('#555555').font('Helvetica-Oblique').fontSize(9).text(PURCHASE_RECORD_DISCLAIMER, left, doc.y + 2, { width: right - left });
    doc.moveDown(0.8);

    doc.fillColor(INK).fontSize(10);
    for (const [label, value] of purchaseRecordFields(row)) {
      const y = doc.y;
      doc.font('Helvetica-Bold').text(`${label}:`, left, y, { width: 150, lineBreak: false });
      doc.font('Helvetica').text(value, left + 155, y, { width: right - left - 155 });
    }
    doc.moveDown(1);

    // Lines table
    const cols = { desc: left, qty: 290, price: 340, tax: 420, total: 480 };
    const header = (): void => {
      const y = doc.y;
      doc.rect(left, y - 3, right - left, 16).fill('#F2F2F0');
      doc.fillColor(INK).font('Helvetica-Bold').fontSize(9);
      doc.text('Description', cols.desc + 4, y, { width: 240, lineBreak: false });
      doc.text('Qty', cols.qty, y, { width: 45, align: 'right', lineBreak: false });
      doc.text('Unit price', cols.price, y, { width: 75, align: 'right', lineBreak: false });
      doc.text('Tax', cols.tax, y, { width: 55, align: 'right', lineBreak: false });
      doc.text('Total', cols.total, y, { width: 75, align: 'right', lineBreak: false });
      doc.y = y + 18;
    };
    header();
    doc.font('Helvetica').fontSize(9);
    for (const item of row.lineItems ?? []) {
      if (doc.y > 740) {
        doc.addPage();
        header();
        doc.font('Helvetica').fontSize(9);
      }
      const y = doc.y;
      const descHeight = doc.heightOfString(pdfSafe(item.description), { width: 240 });
      doc.fillColor(INK);
      doc.text(pdfSafe(item.description), cols.desc + 4, y, { width: 240 });
      doc.text(String(item.qty ?? ''), cols.qty, y, { width: 45, align: 'right', lineBreak: false });
      doc.text(money(item.unitPrice), cols.price, y, { width: 75, align: 'right', lineBreak: false });
      doc.text(money(item.taxAmount), cols.tax, y, { width: 55, align: 'right', lineBreak: false });
      doc.text(money(item.total), cols.total, y, { width: 75, align: 'right', lineBreak: false });
      doc.y = y + Math.max(descHeight, 11) + 4;
    }
    doc.moveDown(0.5);

    // Totals (KRA's totTaxblAmt is VAT-inclusive, so show net = total - VAT)
    const net = Math.round((row.total - row.vat + Number.EPSILON) * 100) / 100;
    const totals: Array<[string, string, boolean]> = [
      ['Subtotal (excl. VAT)', money(net), false],
      ['VAT', money(row.vat), false],
      ['Total', money(row.total), true],
    ];
    if (doc.y > 720) doc.addPage();
    for (const [label, value, bold] of totals) {
      const y = doc.y;
      doc.fillColor(INK).font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(bold ? 11 : 10);
      doc.text(label, 340, y, { width: 135, align: 'right', lineBreak: false });
      doc.text(`KES ${value}`, 480, y, { width: 75, align: 'right', lineBreak: false });
      doc.y = y + (bold ? 16 : 14);
    }

    doc.fillColor('#777777').font('Helvetica').fontSize(8);
    doc.text(PURCHASE_RECORD_FOOTER, left, 785, { width: right - left, align: 'center', lineBreak: false });
    doc.end();
  });
}
